version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=data
    tty: true
    container_name: bx_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
    tty: true
    container_name: bx_adminer
  app:
    build:
      context: ./cmd/bx
    volumes:
      - "./:/go/src/github.com/demsasha4yt/bx-backend-trainee-assignment"
    container_name: bx_app
    ports:
      - "3000:3000"
    tty: true
    links:
      - db
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=test@gmail.com
      - SMTP_PASSWORD=passwords
      - SMTP_SENDER_ADD=test@gmail.com
