CREATE TABLE ads_prices (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	price INT NOT NULL CONSTRAINT price_bigger_zero CHECK(price >= 0),
	datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ad_id BIGINT,
	CONSTRAINT fk_ads
		FOREIGN KEY(ad_id)
			REFERENCES ads(id)
				ON DELETE CASCADE
);
