CREATE TABLE ads (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	avito_id BIGINT NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	actual BOOLEAN DEFAULT true
);
